File cleanup

diff --git a/.github/workflows/ssh-deployment.yml b/.github/workflows/ssh-deployment.yml
--- a/.github/workflows/ssh-deployment.yml
+++ b/.github/workflows/ssh-deployment.yml
@@ -63,15 +63,32 @@ jobs:
     steps:
       - name: Check if all required secrets are set and not empty
         run: |
-          secrets=(DEPLOYMENT_SSH_HOST DEPLOYMENT_SSH_HOST_KNOWN_ENTRY DEPLOYMENT_SSH_USERNAME DEPLOYMENT_SSH_PRIVATE_KEY DEPLOYMENT_PATH DEPLOYMENT_GITHUB_TOKEN)
-          for secret in "${secrets[@]}"; do
-            if [ -z "${{ secrets[$secret] }}" ]; then
-              echo "$secret is not set or is empty. Exiting."
-              exit 1
-            else
-              echo "$secret is set and not empty."
-            fi
-          done
+          if [ -z "${{ secrets.DEPLOYMENT_SSH_HOST }}" ]; then
+            echo "DEPLOYMENT_SSH_HOST is not set or is empty. Exiting."
+            exit 1
+          fi
+          if [ -z "${{ secrets.DEPLOYMENT_SSH_HOST_KNOWN_ENTRY }}" ]; then
+            echo "DEPLOYMENT_SSH_HOST_KNOWN_ENTRY is not set or is empty. Exiting."
+            exit 1
+          fi
+          if [ -z "${{ secrets.DEPLOYMENT_SSH_USERNAME }}" ]; then
+            echo "DEPLOYMENT_SSH_USERNAME is not set or is empty. Exiting."
+            exit 1
+          fi
+          if [ -z "${{ secrets.DEPLOYMENT_SSH_PRIVATE_KEY }}" ]; then
+            echo "DEPLOYMENT_SSH_PRIVATE_KEY is not set or is empty. Exiting."
+            exit 1
+          fi
+          if [ -z "${{ secrets.DEPLOYMENT_PATH }}" ]; then
+            echo "DEPLOYMENT_PATH is not set or is empty. Exiting."
+            exit 1
+          fi
+          if [ -z "${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}" ]; then
+            echo "DEPLOYMENT_GITHUB_TOKEN is not set or is empty. Exiting."
+            exit 1
+          fi
+          echo "All required secrets are set and not empty."
+
       - name: Check user inputs
         run: |
           if [[ "${{ inputs.sshHost }}" == "yes" ]] && \
